version: '3.1'
services:
  apigateway:
    image: devopsfaith/krakend
    volumes:
      - "./krakend:/etc/krakend/"
    command: ["krakend", "run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - "8080:8080"
  backend:
    image: api
    build:
      dockerfile: ./api.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:p0stgr3spass@db:5432/postgres?schema=public"
      COMPLIANCE_API_URL: "https://compliance-api.cubos.io"
      COMPLIANCE_API_USER: "tafm@cin.ufpe.br"
      COMPLIANCE_API_PASSWORD: "1xr2IZ3wS3vtGyIlD6Ew"
      PORT: "3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p0stgr3spass
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"